################################################# ILQR parameters ###########################################
wheelbase: 0.257 #[m]
width: 0.2
length: 0.5

#### ILQR constraints #####
# velocity
v_max: 1 # max long vel [m/s]
v_min: 0 #0.05 # min long vel [m/s]

# steering
delta_min: -0.35  # minimum steering angle [rad]
delta_max: 0.35  # maximum steering angle [rad]

# linear acceleration
a_min: -3.5
a_max: 3.5

# lateral acceleration
alat_max: 5.0

#### ILQR weights #####
w_vel: 2
w_contour: 30
w_theta: 0
w_accel: 1
w_delta: 5

# parameters for barrier functions
q1_v: 0
q2_v: 0
q1_road: 5
q2_road: 5
q1_lat: 1
q2_lat: 5
q1_obs: 0
q2_obs: 0

# ilqr parameters
T: 2
N: 11  # the number of planning steps
max_itr: 50

