############################################ Planning parameters ###########################################
replan_dt:            0.1       # time between replaning [s]
ilqr_params_file:     ""

########################################### Control parameters ##############################################
d_open_loop: [-0.0146, 0.0874, -0.0507, 0.0005, -0.0332, 0.1869, 0.0095, 0.0170, -0.0583, 0.0388]



