############################################ Path parameters ###########################################
path_file:            "configs/outerloop_center_smooth.csv" # path file to load if load_track is true
path_width_R:         0.3       # right track width [m]
path_width_L:         0.3       # left track width [m]
path_loop:           true      # if true, the path is looped

############################################ Planning parameters ###########################################
replan_dt:            0.1       # time between replaning [s]
ilqr_params_file:     ""

########################################### Control parameters ##############################################
d_open_loop: [-0.0146, 0.0874, -0.0507, 0.0005, -0.0332, 0.1869, 0.0095, 0.0170, -0.0583, 0.0388]



